//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CycleApp.App.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CycleApp.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Need restart program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageSetting_Restart {
            get {
                return ResourceManager.GetString("LanguageSetting_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageSetting_Setting {
            get {
                return ResourceManager.GetString("LanguageSetting_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lnaguage Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguageSetting_Title {
            get {
                return ResourceManager.GetString("LanguageSetting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_CloseButton {
            get {
                return ResourceManager.GetString("MainWin_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exercise Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_CycleCountTitle {
            get {
                return ResourceManager.GetString("MainWin_CycleCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_CycleCountUnit {
            get {
                return ResourceManager.GetString("MainWin_CycleCountUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Well Done! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_EndMessage {
            get {
                return ResourceManager.GetString("MainWin_EndMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time to concentrate に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_ExercisesTimeTitle {
            get {
                return ResourceManager.GetString("MainWin_ExercisesTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_ExercisesTimeUnit {
            get {
                return ResourceManager.GetString("MainWin_ExercisesTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lnaguage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_LangSetting {
            get {
                return ResourceManager.GetString("MainWin_LangSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} mor times Cheer Up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_MoreCount {
            get {
                return ResourceManager.GetString("MainWin_MoreCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Count
        ///Remained に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_RemainCountString {
            get {
                return ResourceManager.GetString("MainWin_RemainCountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time to Concentrate
        ///{0} Sec left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_RemainExerciseTimeString {
            get {
                return ResourceManager.GetString("MainWin_RemainExerciseTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time to Rest
        ///{0} Sec left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_RemainRestTimeString {
            get {
                return ResourceManager.GetString("MainWin_RemainRestTimeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time to Rest に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_RestTimeTitle {
            get {
                return ResourceManager.GetString("MainWin_RestTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_RestTimeUnit {
            get {
                return ResourceManager.GetString("MainWin_RestTimeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_StartButton {
            get {
                return ResourceManager.GetString("MainWin_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_StopButton {
            get {
                return ResourceManager.GetString("MainWin_StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always Visible Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWin_TopMost {
            get {
                return ResourceManager.GetString("MainWin_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to disable update program? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update_DisableUpdateMessage {
            get {
                return ResourceManager.GetString("Update_DisableUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update_DisableUpdateTitle {
            get {
                return ResourceManager.GetString("Update_DisableUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to Update this Program?
        ///New version : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update_UpdateMessage {
            get {
                return ResourceManager.GetString("Update_UpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detected new version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Update_UpdateTitle {
            get {
                return ResourceManager.GetString("Update_UpdateTitle", resourceCulture);
            }
        }
    }
}
